const minimist = require("minimist");
const fs = require("fs");
const docx = require("docx");
const PptxGenJS = require("pptxgenjs");
const PDFDocument = require("pdfkit");
const ExcelJS = require("exceljs");

const args = minimist(process.argv.slice(2));
const fileType = args.type;
const title = args.title || "Kolaborate AI Document";
const content = args.content || "No content provided.";
const fileName = `Kolaborate_${fileType.toUpperCase()}_${Date.now()}`;

const brandColor = "2A8A34"; 
const brandHex = "#2A8A34";
const logoPath = "./public/logo.png"; 
const hasLogo = fs.existsSync(logoPath);

async function generateFile() {
    try {
        switch (fileType) {
            case "docx":
                let docChildren = [];
                
                if (hasLogo) {
                    docChildren.push(new docx.Paragraph({
                        alignment: docx.AlignmentType.CENTER,
                        children: [new docx.ImageRun({
                            data: fs.readFileSync(logoPath),
                            transformation: { width: 160, height: 60 }
                        })]
                    }));
                }

                docChildren.push(
                    new docx.Paragraph({ text: title, heading: docx.HeadingLevel.TITLE, alignment: docx.AlignmentType.CENTER }),
                    new docx.Paragraph({ text: "Confidential - Generated by Kolaborate AI Agent", alignment: docx.AlignmentType.CENTER, spacing: { after: 400 } }),
                    ...content.split('\n').filter(line => line.trim()).map(line => 
                        new docx.Paragraph({ text: line.replace(/^#+\s*/, '').replace(/^[-*]\s*/, '• '), spacing: { after: 200 } })
                    )
                );

                const doc = new docx.Document({ sections: [{ properties: {}, children: docChildren }] });
                const buffer = await docx.Packer.toBuffer(doc);
                fs.writeFileSync(`${fileName}.docx`, buffer);
                break;

           case "pptx":
                let pres = new PptxGenJS();
                let titleSlide = pres.addSlide();
                titleSlide.background = { fill: "FFFFFF" }; 
                
                if (hasLogo) {
                    titleSlide.addImage({ path: logoPath, x: 3.25, y: 1.0, w: 3.5, h: 1.2 });
                }

                titleSlide.addText(title, { x: 0.5, y: 2.6, w: 9, fontSize: 38, bold: true, color: brandColor, align: "center" });
                titleSlide.addShape(pres.ShapeType.line, { x: 4, y: 3.6, w: 2, h: 0, line: { color: brandColor, width: 3 } });
                titleSlide.addText("Generated via Kolaborate AI Agent", { x: 0.5, y: 4.0, w: 9, fontSize: 16, color: "888888", align: "center" });

                let slidesData = content.split(/##\s+/).filter(s => s.trim().length > 0);
                if (slidesData.length === 1) slidesData = content.split(/\n{2,}/).filter(s => s.trim().length > 0);

                slidesData.forEach(slideContent => {
                    const lines = slideContent.split('\n').map(l => l.trim()).filter(l => l.length > 0);
                    if(lines.length === 0) return;

                    let slideTitle = lines[0].replace(/^#+\s*/, ''); 
                    let bodyText = lines.slice(1).join('\n').replace(/^[-*]\s*/gm, '• ');

                    // 🚨 THE FIX: Catch massive paragraphs pretending to be titles
                    if (slideTitle.length > 60) {
                        bodyText = slideTitle + (bodyText.length > 0 ? '\n' + bodyText : '');
                        slideTitle = "Key Insights"; // Safe default title
                    }

                    let newSlide = pres.addSlide();
                    newSlide.addShape(pres.ShapeType.rect, { x: 0, y: 0, w: "100%", h: 0.8, fill: brandColor });
                    newSlide.addText(slideTitle, { x: 0.5, y: 0.1, w: 7, h: 0.6, fontSize: 24, bold: true, color: "FFFFFF" });
                    
                    if (hasLogo) {
                        newSlide.addShape(pres.ShapeType.rect, { x: 8.0, y: 0.1, w: 1.8, h: 0.6, fill: "FFFFFF", rectRadius: 0.1 });
                        newSlide.addImage({ path: logoPath, x: 8.15, y: 0.15, w: 1.5, h: 0.5 });
                    }

                    // 🚨 THE FIX: Added autoFit: true so long text shrinks dynamically instead of spilling over!
                    newSlide.addText(bodyText, { x: 0.5, y: 1.2, w: 9, h: 3.5, fontSize: 18, align: "left", valign: "top", autoFit: true });
                    newSlide.addText("Kolaborate Internal Document", { x: 0.5, y: 5.1, w: 4, fontSize: 10, color: "888888", bold: true });
                });

                await pres.writeFile({ fileName: `${fileName}.pptx` });
                break;

            case "pdf":
                const pdf = new PDFDocument({ margin: 50 });
                pdf.pipe(fs.createWriteStream(`${fileName}.pdf`));
                
                pdf.rect(0, 0, pdf.page.width, 80).fill(brandHex);
                
                if (hasLogo) {
                    pdf.image(logoPath, 50, 20, { height: 40 });
                    pdf.fillColor('#ffffff').fontSize(24).font('Helvetica-Bold').text(title, 220, 25, { align: 'left', width: 340 });
                } else {
                    pdf.fillColor('#ffffff').fontSize(24).font('Helvetica-Bold').text(title, 50, 25, { align: 'center' });
                }
                
                pdf.moveDown(3);
                const cleanPdfContent = content.replace(/^#+\s*/gm, '').replace(/^[-*]\s*/gm, '• ');
                pdf.fillColor('#333333').fontSize(12).font('Helvetica').text(cleanPdfContent, { lineGap: 6 });
                pdf.fontSize(10).fillColor('#888888').text('Kolaborate Confidential', 50, pdf.page.height - 50, { align: 'center' });
                pdf.end();
                break;

            case "excel":
                const workbook = new ExcelJS.Workbook();
                const sheet = workbook.addWorksheet("AI Data");
                sheet.columns = [ { key: "title", width: 30 }, { key: "content", width: 100 } ];
                
                let startRow = 1;
                
                if (hasLogo) {
                    const logoId = workbook.addImage({ filename: logoPath, extension: 'png' });
                    sheet.addImage(logoId, { tl: { col: 0, row: 0 }, ext: { width: 160, height: 60 } });
                    startRow = 5; 
                }

                const headerRow = sheet.getRow(startRow);
                headerRow.values = ["Kolaborate Topic", "Generated Content"];
                headerRow.font = { bold: true, color: { argb: 'FFFFFFFF' } };
                headerRow.fill = { type: 'pattern', pattern:'solid', fgColor:{ argb:'FF2A8A34' } };
                
                const dataRow = sheet.getRow(startRow + 1);
                const cleanExcelContent = content.replace(/^#+\s*/gm, '').replace(/^[-*]\s*/gm, '• ');
                dataRow.values = [title, cleanExcelContent];
                dataRow.alignment = { wrapText: true, vertical: 'top' };
                
                await workbook.xlsx.writeFile(`${fileName}.xlsx`);
                break;

            default:
                process.exit(1);
        }
        console.log(`${fileName}.${fileType}`);
    } catch (error) {
        console.error("Error generating file:", error);
    }
}

generateFile();